CREATE TYPE IF NOT EXISTS expense_type AS ENUM (
    '',
    '',
    '',
    '',
    ''
);

CREATE TABLE IF EXISTS "expenses"(
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" INTEGER 
        REFERENCES "users"(id) ON DELETE CASCADE NOT NULL,
    "expense_amount" NUMERIC(12,2) CHECK (income_amount >= 0) DEFAULT 0 NOT NULL,\
    "expense_category" expense_type NOT NULL,
    "date_created" TIMESTAMP DEFAULT now() NOT NULL
);